name: ffuf_bootcamp_exam

description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  cloud_firestore: ^3.1.17
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  async_redux: ^15.0.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100

        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300

        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400

        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
          
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
